### ISSUE TITLE
Please compare with MediatR (and possibly other existing libraries)

### ISSUE THREAD

**Issue by codingawayy** [danielwertheim/routemeister#1]
Good start. Could you please explain the core differences between routemeister and MediatR. Don't want to discourage any further work, but just need to understand how the two relate. Cheers!

**Comment by danielwertheim** [comment]
Not familiar enough with MediatR so I will not make any statements. RouteMeister is meant to only provide you with finding handlers and construct routes from this so that you (it) can route messages to handlers internally. So it can work as a complement to something where you e.g. can not use a full fledged bus like MassTransit etc. E.g. ActiveMQ consumers or custom web socket servers etc. That's what I use it for. So the scope of RouteMesiter will not be so much more. Just improvements. Hooking in loggers and allowing synchronous routing, then potentially a few more routers controlling parallelism etc. Maybe, de-duplication etc.

**Comment by danielwertheim** [comment]
@niaher feel free to close. I know the answer is vague but I have no better answer as of now.

**Comment by danielwertheim** [comment]
@niaher did a writeup of Routemeister and MediatR. Usage and some timings that it takes to route something: http://danielwertheim.se/reply-to-please-compare-routemesiter-with-mediatr/

**Comment by codingawayy** [comment]
Appreciate it. Very detailed and useful
